### ISSUE TITLE
Sending data to the server

### ISSUE THREAD

**Issue by darkhorse2013** [CaffeinaLab/raven-titanium#1]
What is the titanium equivalent for this python line of code:

sentry = Sentry(dsn='http://public_key:secret_key@example.com/1')

So that I can send crash data to the server?

Thanks

**Comment by kopiro** [comment]
Hi, I'm sorry if there's no documentation, but this project is still in progress.
Anyway, the syntax is:

``` js
require('ti.raven').initialize('YOUR_DSN');
```

Try and let us know if something bad happens :dancer:

**Comment by darkhorse2013** [comment]
Hi Kopiro,

Thanks for this. This is my line of code:

var raven_titanium = require('ti.raven').initialize('YOUR_DSN');
Ti.API.info("module is => " + raven_titanium);
When I print the module out in the console it has 

module is = > undefined

However when I do this:

var raven_titanium = require('ti.raven');
Ti.API.info("module is => " + raven_titanium);

The module is not undefined. Are you sure this is the right code?

**Comment by kopiro** [comment]
Wait,

`initialize` it's a void function, so it doesn't return the module.

The right code could be:

``` js
var raven_titanium = require('ti.raven');
raven_titanium.initialize('YOUR_DSN');
Ti.API.info("module is => " + raven_titanium);
```

;)-

**Comment by darkhorse2013** [comment]
Thanks, that works now
